version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: petspa_postgres
    environment:
      POSTGRES_DB: petspa_db
      POSTGRES_USER: petspa_user
      POSTGRES_PASSWORD: petspa_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 